version: '3.8'
services:
  mysql:
    container_name: mysql-1
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: short_urls
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - ./src/short_url/Database/import.sql:/docker-entrypoint-initdb.d/import.sql
    command: --init-file /docker-entrypoint-initdb.d/import.sql

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5341:80"
    volumes:
      - ./seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_UI=1

  web-api:
    container_name: web-api
    # build:
    #   context: .
    #   dockerfile: ./src/short_url/Dockerfile
    image: dangdan2807/short-url:v1.1
    ports:
      - "13080:80"
      - "13443:443"
    depends_on:
      - mysql
      - seq
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=short_urls;User=admin;Password=123456
