version: '3.8'
services:
  mysql:
    container_name: mysql-1
    image: mysql:8.0
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: short_urls
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    volumes:
      - ./src/short_url/Database/import.sql:/docker-entrypoint-initdb.d/import.sql
    command: --init-file /docker-entrypoint-initdb.d/import.sql

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - '5341:80'
    volumes:
      - ./src/seq-data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_UI=1

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - '16379:6379'
    volumes:
      - ./src/redis-data:/data

  backend:
    container_name: short-link-be
    image: dangdan2807/short-url-be
    ports:
      - '5192:80'
      - '7167:443'
    depends_on:
      - mysql
      - seq
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql-1;port=3306;database=short_urls;user=admin;password=123456;
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RedisPassword=
      - ConnectionStrings__Seq=http://seq:5341
      - Serilog__WriteTo[1]__Args__serverUrl=http://seq:5341

  frontend:
    container_name: short-link-fe-nginx
    image: dangdan2807/short-url-fe
    ports:
      - '44481:80'
    environment:
      - REACT_APP_URL_BACKEND=http://short-link-be:80/api


# // "Redis": "redis-15338.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:15338",
#     // "RedisPassword": "YJTNO4B9ArbcXQ4MQ1nvSMaOzjWznjop",